CREATE TABLE `posts` (
  `id` uuid NOT NULL,
  `title` varchar(255) NOT NULL,
  `config` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;insert into `posts` (`config`, `created_at`, `id`, `title`) values ('{   \"summary\": \"Dive into the history of artificial intelligence, from ancient myths to the pivotal roles of McCarthy and Turing in shaping AI as we know it.\",   \"content\": \"On a serene morning, the sun rises over the horizon, casting its golden rays across the tranquil countryside. Fields of vibrant green stretch as far as the eye can see, dotted with colorful wildflowers swaying gently in the breeze. A gentle stream meanders through the landscape, its crystal-clear waters glistening in the sunlight. In the distance, majestic mountains rise majestically, their peaks kissed by wisps of fluffy white clouds. The air is filled with the sweet fragrance of blooming flowers and the earthy scent of the forest. Birds sing joyously in the trees, their melodic tunes blending harmoniously with the rustle of leaves in the wind. As the day unfolds, nature comes alive with a symphony of sights, sounds, and scents, painting a picture of serenity and beauty that soothes the soul.\",   \"image\": \"uploads/9c4689ee01a3ea469f2a5f745795adb3.jpg\" }', '2024-04-25 14:09:31', '6409d83a-4d62-48ff-9050-37d10bd6780a', 'Who was the first person to think of AI?');
insert into `posts` (`config`, `created_at`, `id`, `title`) values ('{\"summary\":\"On a serene morning, the sun rises over the horizon, casting its golden rays across the tranquil countryside. Fields of vibrant green stretch as far as the eye can see, dotted with colorful wildflowers swaying gently in the breeze\",\"content\":\"<p> A gentle stream meanders through the landscape, its crystal-clear waters glistening in the sunlight. In the distance, majestic mountains rise majestically, their peaks kissed by wisps of fluffy white clouds. The air is filled with the sweet fragrance of blooming flowers and the earthy scent of the forest. Birds sing joyously in the trees, their melodic tunes blending harmoniously with the rustle of leaves in the wind. As the day unfolds, nature comes alive with a symphony of sights, sounds, and scents, painting a picture of serenity and beauty that soothes the soul.</p>\",\"image\":\"uploads/18fdc4d648b8f768feebbd8de14a4dd5.jpg\"}', '2024-04-25 19:11:38', '5bcf50aa-ead1-4d35-bf47-9c67797a082f', 'In a bustling city, the streets teem with life');
insert into `posts` (`config`, `created_at`, `id`, `title`) values ('{   \"summary\": \"Dive into the history of artificial intelligence, from ancient myths to the pivotal roles of McCarthy and Turing in shaping AI as we know it.\",   \"content\": \"On a serene morning, the sun rises over the horizon, casting its golden rays across the tranquil countryside. Fields of vibrant green stretch as far as the eye can see, dotted with colorful wildflowers swaying gently in the breeze. A gentle stream meanders through the landscape, its crystal-clear waters glistening in the sunlight. In the distance, majestic mountains rise majestically, their peaks kissed by wisps of fluffy white clouds. The air is filled with the sweet fragrance of blooming flowers and the earthy scent of the forest. Birds sing joyously in the trees, their melodic tunes blending harmoniously with the rustle of leaves in the wind. As the day unfolds, nature comes alive with a symphony of sights, sounds, and scents, painting a picture of serenity and beauty that soothes the soul.\",   \"image\": \"uploads/9c4689ee01a3ea469f2a5f745795adb3.jpg\" }', '2024-04-25 14:12:18', '288d7bbe-2881-4a39-815f-cc429ab3e08f', 'Who was the first person to think of AI?');
